#!/bin/bash

all_vars=("PYTHONHOME" "PYTHONPATH" "PYTHONSTARTUP" "PYTHONY2K" 
    "PYTHONOPTIMIZE" "PYTHONDEBUG" "PYTHONINSPECT" "PYTHONUNBUFFERED" 
    "PYTHONVERBOSE" "PYTHONCASEOK" "PYTHONDONTWRITEBYTECODE"
    "PYTHONHASHSEED" "PYTHONIOENCODING" "PYTHONNOUSERSITE" "PYTHONUSERBASE"
    "PYTHONEXECUTABLE" "PYTHONWARNINGS" "PYTHONHTTPSVERIFY" "PYTHONTHREADDEBUG"
    "PYTHONDUMPREFS" "PYTHONMALLOCSTATS" "PYTHONSHOWALLOCCOUNT"
    "PYTHONSHOWREFCOUNT")

for var_name in ${all_vars[@]}; do
    echo $var_name
    find . -type f -name "*" ! -name "change_env_vars.sh" ! -path "./.git/*" -exec sed -b -i'' -e "s/${var_name}/OM${var_name}/g" {} +
done
